### PR TITLE
Upgrade to 1.26 without force-push

### PR DESCRIPTION
**Pull request by milkie**
I reverted all the commits in develop that didn't exist in release/v1.26, except for the 8 that we think we need to preserve.  I also cherry-picked 2 commits from Tristan for the versioning enhancements.

### CODE REVIEW

**Comment by milkie** [comment]
Ok, force-pushed a new set of commits that exactly matches the files changed in Jamie's PR

**Comment by visualzhou** [comment]
v1.26 would diverge from `main` since it's a release branch. Does this mean we'd have to do the same on the next upgrade?

**Comment by milkie** [comment]
> v1.26 would diverge from `main` since it's a release branch. Does this mean we'd have to do the same on the next upgrade?

Oh I thought we created the release/v1.26 branch by just syncing it to a v1.26 tag on the main envoy branch.  Does Envoy actually create release branches?

**Comment by visualzhou** [comment]
The upstream has a `release/v1.26` branch ([link](https://github.com/envoyproxy/envoy/tree/release/v1.26)), like how MongoDB has `v5.0` branch to enable backports. It already has [78 commits ahead](https://github.com/envoyproxy/envoy/compare/main...release/v1.26) of `main` and also many commit behind. I think we will update to minor versions, like `1.26.2` in the future and also major versions that is part of the `main` history, like `1.27.0`.

**Comment by milkie** [comment]
I wonder if we should branch this repo in kind then, in order to avoid losing history with force-pushing.  This means when we do future upgrades, we make a new branch from `develop` and then cherry-pick the commits from the old release branch that we want to keep.

**Comment by milkie** [comment]
Indeed Siyuan's comment above has convinced me that the proposal in this PR is unworkable.  We're going to go back to Jamie's PR instead.

**Pull request closed without merging**
