### PR TITLE
CLOUDP-173167: Update serverless-proxy version format to follow the format of envoy-serverless

### PR DESCRIPTION
**Pull request by TristanWedderburn**
Commit Message: Created `serverless-proxy/v1.26.0` branch in envoy-serverless to track patches on top of `v1.26.0` envoy branch
Additional Description: 
Risk Level: low
Testing: Updated `version_out_test.sh`
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by visualzhou** [comment]
Do we have a patch build? Is there an example of the `--version` command line output?

**Review by JamesHeppenstall — COMMENTED** [review]
Responding to both this PR and https://github.com/10gen/serverless-proxy/pull/104.

I'm a little confused with this approach since I thought all we needed to do in [CLOUDP-173167](https://jira.mongodb.org/browse/CLOUDP-173167) was update the name of the binary [here](https://github.com/10gen/serverless-proxy/blob/main/evergreen/archive_evergreen.sh#L14). Is anyone using the output of `bazel-bin/envoy --version`?

Also a few more comments:
1. I don't think we want to be creating custom release branches in `envoy-serverless`, adding commits to them, and then pointing `serverless-proxy` to those branches. The initial thinking was to always point `serverless-proxy` to the `develop` branch and periodically fast-forward it when (i) Envoy is updated or (ii) we need new commits on the branch. I feel like the cognitive overhead of multiple branches `serverless-proxy` can point to will make reasoning about it more difficult.
2. I don't think we want to be creating tags in `serverless-proxy` as part of our release process. Ideally, we want to mimic the release process of `mms` and create branches of the form `v20230101`. What is the tag being used for?

**Note:** The reason we're not pointing `serverless-proxy` to the `develop` branch yet is that we're waiting for [CLOUDP-150797](https://jira.mongodb.org/browse/CLOUDP-150797) to be done (I guess the ticket should go all the way to `v1.26` now).

**Comment by TristanWedderburn** [comment]
> Do we have a patch build? Is there an example of the `--version` command line output?

Great point, we can find a patch build in the compile task [here](https://spruce.mongodb.com/task/serverless_proxy_al2_aarch64_required_compile_patch_6aa8a66c9bc1abe6e8f34df84970138f50f012b2_645a9026d1fe07b7538d28d5_23_05_09_18_25_43/files?execution=0) from serverless-proxy.

The output from serverless-proxy binary can be found from the file name, e.g. `serverless-proxy-1.26.0-2-gfc01689.al2.aarch64.tar.gz`, which corresponds to the commit [serverless-proxy-1.26.0-2-gfc01689.al2.aarch64.tar.gz](https://mongodb-mms-build-envoy-serverless.s3.amazonaws.com/serverless-proxy/build/serverless_proxy_al2_aarch64_required_patch_6aa8a66c9bc1abe6e8f34df84970138f50f012b2_645a9026d1fe07b7538d28d5_23_05_09_18_25_43/serverless-proxy-1.26.0-2-gfc01689.al2.aarch64.tar.gz), but I capture output from my terminal in the PR description [here](https://github.com/10gen/serverless-proxy/pull/104#issue-1702539828)

**Comment by TristanWedderburn** [comment]
> I'm a little confused with this approach since I thought all we needed to do in [CLOUDP-173167](https://jira.mongodb.org/browse/CLOUDP-173167) was update the name of the binary [here](https://github.com/10gen/serverless-proxy/blob/main/evergreen/archive_evergreen.sh#L14). Is anyone using the output of `bazel-bin/envoy --version`?

Great point, we also need to update the `--version` output because the automation agent uses it to compare envoy binaries in tests, what was implemented in [CLOUDP-137031](https://jira.mongodb.org/browse/CLOUDP-137031) 🙂

**Comment by TristanWedderburn** [comment]
> Also a few more comments:
> 
> 1. I don't think we want to be creating custom release branches in `envoy-serverless`, adding commits to them, and then pointing `serverless-proxy` to those branches. The initial thinking was to always point `serverless-proxy` to the `develop` branch and periodically fast-forward it when (i) Envoy is updated or (ii) we need new commits on the branch. I feel like the cognitive overhead of multiple branches `serverless-proxy` can point to will make reasoning about it more difficult.
> 2. I don't think we want to be creating tags in `serverless-proxy` as part of our release process. Ideally, we want to mimic the release process of `mms` and create branches of the form `v20230101`. What is the tag being used for?
> 
> **Note:** The reason we're not pointing `serverless-proxy` to the `develop` branch yet is that we're waiting for [CLOUDP-150797](https://jira.mongodb.org/browse/CLOUDP-150797) to be done (I guess the ticket should go all the way to `v1.26` now).

1. That's a great point as well. I agree with the intended use cases for the envoy-serverless repo. Based on my understanding, I thought it would be cleaner and clearer if we created a new branch in envoy-serverless that tracked the new version, mirroring the envoy upstream release process, and then patched it with things that we don't intend to merge upstream? e.g. this `--version` update. Otherwise, things should be in serverless-proxy?

2. I've also used the tag in `serverless-proxy` to more clearly indicate when we've upgraded the submodule version. We are also using the tag so that we can use the same `git describe --tags --dirty --always --match 'v[0-9]*' --abbrev=7 | cut -c 2-` command to get the binary name, directly in serverless-proxy.

Would love to get your thoughts on that 🙂

**Comment by TristanWedderburn** [comment]
Per offline convo with @JamesHeppenstall , we will proceed with this implementation. Updated the target branch to `release/v1.26`. I will also update https://github.com/10gen/serverless-proxy/pull/104 to point to this updated branch once it's merged 🙂

**Review by JamesHeppenstall — APPROVED** [review]
LGTM 👍 great work with this btw!

**Pull request merged**
